/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Runemark (https://sketchfab.com/skyie)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/47512c994e70431d853a9e3dcaa3baba
title: Pin for 3D clothing
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Pin({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Pin.gltf')
  return (
    <group 
      ref={group} 
      {...props} 
      dispose={null} 
      receiveShadow
      castShadow
    >
      <group rotation={[-Math.PI / 8, 0, 0]} >
        <mesh geometry={nodes.mesh_0.geometry} material={materials.None} />
      </group>
    </group>
  )
}

useGLTF.preload('/Pin.gltf')
